services:
  - type: web
    name: eloy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001
  
  - type: web
    name: eloy-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist