// Auto-fill configuration
export const autoFillConfig = {
  // Fixed nomination details
  category: "ELOY Award for Entrepreneur",
  
  // Fixed nominee details (the person being nominated)
  nominee_first: "Chioma",
  nominee_last: "Okafor",
  nominee_instagram: "@chiomaokafor",
  nominee_linkedin: "https://linkedin.com/in/chiomaokafor",
  nominee_email: "chioma.okafor@gmail.com",
  nominee_phone: "+2348123456789",
  nominee_website: "",
  reason: "Outstanding leadership and innovation in business development across Nigeria and West Africa.",
}

// Nigerian names for random generation
export const nigerianNames = {
  firstNames: [
    "Adunni", "Bukola", "Chioma", "Damilola", "Ebere", "Folake", "Grace", "Hauwa", "Ifeoma", "Jumoke",
    "Kemi", "Lola", "Maryam", "Ngozi", "Oluchi", "Patience", "Queen", "Rashida", "Stella", "Tope",
    "Uche", "Victoria", "Wunmi", "Yemi", "Zainab", "Adaeze", "Blessing", "Chiamaka", "Deborah", "Esther",
    "Fatima", "Gloria", "Helen", "Ifunanya", "Joy", "Khadijah", "Loveth", "Mercy", "Nneka", "Omolara",
    "Peace", "Abigail", "Adanna", "Adunola", "Aisha", "Amaka", "Amina", "Anita", "Anthonia", "Asha",
    "Asabe", "Asmau", "Awele", "Ayaba", "Ayesha", "Azuka", "Bimbo", "Bunmi", "Chidimma", "Chinelo",
    "Chinwe", "Chinyere", "Comfort", "Dupe", "Ejiro", "Emem", "Enitan", "Ese", "Funmi", "Gbemi",
    "Hadiza", "Halima", "Hauwa", "Ibukun", "Idowu", "Ijeoma", "Ikechukwu", "Imelda", "Iniobong", "Isoken",
    "Itunu", "Ivie", "Iyabo", "Jemima", "Juliana", "Justina", "Kanyinsola", "Kehinde", "Kelechi", "Kemi",
    "Khadijat", "Kimberly", "Laide", "Latifat", "Lilian", "Lydia", "Mabel", "Magdalene", "Mariam", "Maureen",
    "Modupe", "Mojisola", "Monisola", "Motunrayo", "Nana", "Nkechi", "Nkiru", "Nnenna", "Nonso", "Nora",
    "Obiageli", "Obianuju", "Ogechi", "Ogochukwu", "Olamide", "Olayinka", "Olubunmi", "Olufunke", "Olumide", "Oluwatosin",
    "Omolola", "Omotola", "Onome", "Opeyemi", "Osaremen", "Oyinkan", "Peculiar", "Philomena", "Precious", "Princess",
    "Priscilla", "Promise", "Rachael", "Rebecca", "Rita", "Rosemary", "Ruth", "Salome", "Sandra", "Sarah",
    "Sekinat", "Shade", "Shola", "Simi", "Sola", "Suliat", "Taiwo", "Temilola", "Temitope", "Titilayo",
    "Tolani", "Tolulope", "Tomi", "Tosin", "Treasure", "Tumininu", "Tunmise", "Udoka", "Ugochi", "Ujunwa",
    "Uloma", "Unoma", "Urenna", "Uzoma", "Vanessa", "Vera", "Veronica", "Vivian", "Winifred", "Yetunde"
  ],
  lastNames: [
    "Adebayo", "Bello", "Chukwu", "Danjuma", "Emeka", "Fashola", "Garba", "Hassan", "Ibrahim", "Jide",
    "Kalu", "Lawal", "Mohammed", "Nwosu", "Okafor", "Patel", "Quadri", "Rasheed", "Sani", "Tunde",
    "Usman", "Vincent", "Williams", "Yakubu", "Zubair", "Akinola", "Babatunde", "Chinedu", "Daniel", "Ezekiel",
    "Felix", "George", "Henry", "Isaac", "James", "Kenneth", "Lawrence", "Michael", "Nicholas", "Oscar",
    "Peter", "Abdullahi", "Abubakar", "Achebe", "Adamu", "Adebisi", "Adegoke", "Adeleke", "Ademola", "Adeola",
    "Adesanya", "Adeyemi", "Agbaje", "Agboola", "Ahmed", "Ajayi", "Akande", "Akinwale", "Akinyemi", "Alabi",
    "Alao", "Aliyu", "Amadi", "Anyanwu", "Aremu", "Asaolu", "Awolowo", "Ayodele", "Azikiwe", "Bakare",
    "Bamidele", "Bassey", "Chima", "Dada", "Dare", "Dauda", "David", "Ebong", "Egwu", "Ejiofor",
    "Ekwueme", "Emeka", "Eze", "Ezeh", "Fajana", "Falana", "Femi", "Gbenga", "Haruna", "Idris",
    "Igwe", "Ikechukwu", "Ikenna", "Ikenga", "Imo", "Isah", "Isiaka", "Jaja", "Johnson", "Joseph",
    "Kalu", "Kamalu", "Kanu", "Kayode", "Kingsley", "Kola", "Kunle", "Lateef", "Madu", "Maina",
    "Makinde", "Mamman", "Musa", "Nduka", "Nnamdi", "Nnanna", "Nwachukwu", "Nwankwo", "Nwosu", "Obasi",
    "Obi", "Obiora", "Odunsi", "Ogbonna", "Ogbu", "Ogundimu", "Ogunleye", "Okafor", "Okechukwu", "Okeke",
    "Okonkwo", "Okoro", "Okwu", "Olabode", "Oladele", "Oladipo", "Olajide", "Olaleye", "Olamide", "Olanrewaju",
    "Olasunkanmi", "Olatunji", "Olawale", "Olayemi", "Olayinka", "Olumide", "Olusegun", "Oluwatobi", "Omeje", "Onuoha",
    "Onyeka", "Onyema", "Opara", "Orji", "Osaze", "Oshodi", "Otedola", "Owolabi", "Oyedepo", "Oyewole",
    "Salami", "Samuel", "Sanusi", "Shehu", "Sule", "Taiwo", "Tanko", "Thomas", "Tijani", "Udoh",
    "Ugwu", "Umar", "Umaru", "Uzoma", "Wale", "Yaro", "Yusuf", "Zakari", "Zango", "Zubair"
  ]
}

// Personal finance and money management focused nomination reasons
export const nominationReasons = [
  "She has taught countless people how to build a simple budget that actually works, and for the first time many of us feel in control of our money.",
  "She inspires women entrepreneurs by showing them how to separate personal and business finances so they can finally see profits clearly.",
  "Through her practical money lessons, she’s helped entire families start saving for school fees, medical needs, and long-term goals.",
  "She speaks with so much passion about financial freedom that you leave her sessions believing it’s possible for you too.",
  "Her debt repayment strategies have literally helped people escape the crushing cycle of owing money year after year.",
  "She teaches young people that even small savings matter, planting habits that will serve them for life.",
  "She has a unique way of making financial literacy feel empowering instead of overwhelming.",
  "Because of her teaching, I opened my first savings account and learned the discipline of setting money aside monthly.",
  "She’s helped communities understand that money management isn’t just about numbers—it’s about dignity, security, and choices.",
  "Her workshops on multiple income streams have given people real, practical ways to earn beyond their main salary.",
  "She shares her own experiences with money mistakes, which makes her lessons relatable and builds trust.",
  "Because of her, so many Nigerians now understand how to plan for retirement instead of fearing old age.",
  "She has given ordinary people access to knowledge about investing that was once reserved for the wealthy.",
  "She teaches couples how to manage money together without constant arguments, saving both relationships and finances.",
  "Her guidance on emergency funds has saved families from financial disaster during job losses and medical crises.",
  "She’s a consistent voice reminding us that financial education is the key to breaking cycles of poverty.",
  "Through her clear teaching, young professionals are now learning to invest early instead of waiting until later in life.",
  "She uses simple, everyday examples to explain concepts like inflation, compound interest, and diversification.",
  "Her financial planning sessions empower people to dream bigger, because they finally have a roadmap to achieve those dreams.",
  "She’s helped small business owners track expenses, cut waste, and finally start paying themselves a salary.",
  "Because of her speaking tours, even people in rural areas now understand the importance of saving and investing.",
  "She is bold about teaching women to control their own money, which is changing the culture around financial independence.",
  "She constantly emphasizes that money is a tool for freedom, not just survival.",
  "Her training programs have helped civil servants manage modest salaries in a way that still builds long-term wealth.",
  "She explains complex investment opportunities in plain language, so ordinary people feel confident to take part.",
  "She doesn’t just lecture; she listens, which makes her financial advice tailored and impactful.",
  "Her guidance helped me finally set financial goals and actually reach them step by step.",
  "She’s opened the eyes of teenagers and students to the power of starting small with money.",
  "She’s taught parents how to prepare financially for their children’s education without drowning in debt.",
  "Her impact is clear: people walk into her sessions stressed about money and walk out with hope, a plan, and confidence.",
  "She makes financial conversations feel safe, so people can ask the questions they were once embarrassed to admit they didn’t know.",
  "She believes no one is ‘bad with money,’ only undereducated, and that message is liberating.",
  "Her teachings on side hustles have helped many start small businesses that now provide steady income.",
  "She knows how to turn fear about money into curiosity and action.",
  "Because of her, I now track every expense, and I’ve managed to save more in six months than I did in three years.",
  "She helps people understand that building wealth is a marathon, not a sprint.",
  "She emphasizes the importance of giving and generosity as part of a healthy financial life.",
  "She’s shown that even low-income earners can build wealth if they learn to manage and grow money wisely.",
  "Her digital content has reached thousands who couldn’t attend live workshops but still benefit from her knowledge.",
  "She turns dry financial topics into engaging stories that stick with you long after her talks.",
  "She’s given me the confidence to start investing, something I thought was only for rich people.",
  "Her influence has helped more women start contributing to household financial decisions with confidence.",
  "She reminds people that true financial success isn’t about competing with others but about reaching your own goals.",
  "Her encouragement made me set up an automatic savings plan—I hardly notice the money leaving, but the balance keeps growing.",
  "She gives practical advice that fits the Nigerian context, not imported theories that don’t work here.",
  "She inspires trust because she lives simply and shows that financial wisdom is about values, not just numbers.",
  "Her teaching on financial discipline helped me cut unnecessary spending without feeling deprived.",
  "She’s taught artisans and traders how to record daily earnings, which has changed how they run their businesses.",
  "She constantly reminds people that money is a servant, not a master.",
  "Her investment clubs have helped groups of people pool funds to achieve things none could have done alone.",
  "She pushes people to think long-term, whether it’s retirement, children’s future, or building generational wealth.",
  "Her financial advice has stopped families from falling into predatory loan traps.",
  "She makes it clear that financial independence is possible for women, even if society suggests otherwise.",
  "Because of her teaching, I finally paid off my credit card debt and stayed debt-free.",
  "She encourages saving for emergencies before chasing investments, which has saved many from unnecessary risks.",
  "She teaches that building wealth isn’t about luck—it’s about habits.",
  "She gives people courage to talk about money openly with their families.",
  "Her guidance has made people more confident in negotiating salaries and business deals.",
  "She helps people understand that wealth is built little by little, not overnight.",
  "She once said, ‘Your money should be working harder than you,’ and that shifted how I think about investing.",
  "She’s taught countless people how to avoid lifestyle inflation and stay grounded as they earn more.",
  "Her mentorship has turned people who hated spreadsheets into confident financial planners.",
  "She breaks down retirement savings into small, doable steps that don’t feel overwhelming.",
  "She makes every student feel seen and heard, no matter their income level.",
  "Her teaching on passive income inspired many to explore investments that now support them monthly.",
  "She’s helped young adults understand credit and avoid the mistakes their parents made.",
  "She always insists that money is about freedom of choice, not material things.",
  "Her practical tips on reducing expenses saved me over ₦50,000 in just three months.",
  "She helps parents teach kids about money early, creating a generation of financially literate youth.",
  "She doesn’t just motivate; she gives people step-by-step systems that actually work.",
  "Because of her, people have learned to prioritize financial goals instead of chasing everything at once.",
  "She teaches how to balance giving, saving, and spending in a healthy way.",
  "She’s built a community where people share wins and struggles openly without shame.",
  "Her podcasts and online talks have reached people far beyond her local community.",
  "She always reminds us that even small amounts invested consistently grow into something big.",
  "She challenges people to think about their money legacy—what they’ll leave behind.",
  "She teaches risk management in a way that helps families protect what they’ve worked for.",
  "She has transformed countless people’s relationship with money from fear to empowerment.",
  "Her lessons on insurance have saved families from being wiped out financially during crises.",
  "She’s helped people stop the cycle of living paycheck to paycheck.",
  "She explains that money is not the goal—it’s a tool to reach your real goals.",
  "She’s shown that financial literacy is a form of self-care and empowerment.",
  "Her classes give people confidence to talk to bankers, investors, and employers without fear.",
  "She’s helped people finally understand the stock market in simple terms.",
  "Her teaching has made investing feel accessible to everyday Nigerians.",
  "She once told us, ‘Money grows where it is respected,’ and that line has stayed with me.",
  "Her passion for financial education is contagious—you leave her talks energized to take action.",
  "She’s taught people how to use technology to track and grow their money.",
  "Her guidance has made it easier for people to plan for major life events without financial stress.",
  "She insists that financial stability isn’t selfish; it allows you to help others more.",
  "Her mentorship has created ripple effects—people she taught are now teaching others.",
  "She helps people see money as a pathway to peace, not constant stress.",
  "Her advice helped me avoid a bad investment that would have cost me everything.",
  "She’s trained students to think about money differently, building financial resilience early.",
  "She always says, ‘Wealth is not about income, it’s about what you keep.’",
  "Her training gave me the courage to finally start that side hustle I’d been dreaming of.",
  "She teaches that good money management is a form of freedom and respect for yourself.",
  "She’s built confidence in people who thought they were ‘bad with money.’",
  "Her lessons have turned fear into action for so many of us.",
  "She constantly reminds us that wealth is built slowly and intentionally.",
  "Her community-building approach has made financial literacy a shared journey, not a lonely struggle.",
  "She always backs her teaching with real-life examples that make sense in our context.",
  "She’s given us practical ways to protect wealth from inflation and uncertainty.",
  "Her guidance has helped countless people avoid scams and financial traps.",
  "She believes everyone deserves financial education, no matter their income or background.",
  "She’s helped families build systems to track spending together.",
  "Her work has empowered many women to leave abusive relationships because they could stand financially.",
  "She breaks money myths that hold people back from growing wealth.",
  "She believes every naira should have a purpose, and she teaches you how to assign it one.",
  "Her clear teaching makes complex topics like taxes understandable.",
  "She encourages people to invest in their skills as much as their money.",
  "She’s helped people feel hopeful about their financial future again.",
  "Her emphasis on generational wealth has made families start planning beyond themselves.",
  "She teaches delayed gratification in a way that feels empowering, not restrictive.",
  "She’s guided people to align their financial goals with their personal values.",
  "She emphasizes that money is not evil—it’s how you use it that matters.",
  "Her advice has helped families build wealth without losing their peace.",
  "She has made people understand that financial literacy is as essential as health literacy.",
  "She’s taught us that wealth isn’t just about numbers—it’s about freedom, peace, and purpose.",
  "She continues to inspire thousands to take control of their financial journey every single day.",
  "She has taught countless people how to build a simple budget that actually works, and for the first time many of us feel in control of our money.",
  "She inspires women entrepreneurs by showing them how to separate personal and business finances so they can finally see profits clearly.",
  "Through her practical money lessons, she’s helped entire families start saving for school fees, medical needs, and long-term goals.",
  "She speaks with so much passion about financial freedom that you leave her sessions believing it’s possible for you too.",
  "Her debt repayment strategies have literally helped people escape the crushing cycle of owing money year after year.",
  "She teaches young people that even small savings matter, planting habits that will serve them for life.",
  "She has a unique way of making financial literacy feel empowering instead of overwhelming.",
  "Because of her teaching, I opened my first savings account and learned the discipline of setting money aside monthly.",
  "She’s helped communities understand that money management isn’t just about numbers—it’s about dignity, security, and choices.",
  "Her workshops on multiple income streams have given people real, practical ways to earn beyond their main salary.",
  "She shares her own experiences with money mistakes, which makes her lessons relatable and builds trust.",
  "Because of her, so many Nigerians now understand how to plan for retirement instead of fearing old age.",
  "She has given ordinary people access to knowledge about investing that was once reserved for the wealthy.",
  "She teaches couples how to manage money together without constant arguments, saving both relationships and finances.",
  "Her guidance on emergency funds has saved families from financial disaster during job losses and medical crises.",
  "She’s a consistent voice reminding us that financial education is the key to breaking cycles of poverty.",
  "Through her clear teaching, young professionals are now learning to invest early instead of waiting until later in life.",
  "She uses simple, everyday examples to explain concepts like inflation, compound interest, and diversification.",
  "Her financial planning sessions empower people to dream bigger, because they finally have a roadmap to achieve those dreams.",
  "She’s helped small business owners track expenses, cut waste, and finally start paying themselves a salary.",
  "Because of her speaking tours, even people in rural areas now understand the importance of saving and investing.",
  "She is bold about teaching women to control their own money, which is changing the culture around financial independence.",
  "She constantly emphasizes that money is a tool for freedom, not just survival.",
  "Her training programs have helped civil servants manage modest salaries in a way that still builds long-term wealth.",
  "She explains complex investment opportunities in plain language, so ordinary people feel confident to take part.",
  "She doesn’t just lecture; she listens, which makes her financial advice tailored and impactful.",
  "Her guidance helped me finally set financial goals and actually reach them step by step.",
  "She’s opened the eyes of teenagers and students to the power of starting small with money.",
  "She’s taught parents how to prepare financially for their children’s education without drowning in debt.",
  "Her impact is clear: people walk into her sessions stressed about money and walk out with hope, a plan, and confidence.","She is an exceptional personal finance educator who has transformed thousands of lives through practical money management workshops across Nigeria.",
"She is an outstanding financial literacy advocate teaching communities how to build wealth through smart budgeting and investment strategies.",
"She uses a revolutionary approach to financial education, helping families break cycles of poverty through proper money management.",
"She pioneers teaching women entrepreneurs how to manage business finances and grow their income streams.",
"She has a transformative impact on youth financial literacy, teaching young people the fundamentals of saving, investing, and building wealth.",
"She makes an exceptional contribution to rural communities through mobile financial education programs that teach practical money skills.",
"She demonstrates outstanding leadership in developing accessible financial education content that helps ordinary Nigerians understand money management.",
"She is revolutionary in teaching debt management strategies that have helped thousands escape financial bondage.",
"She pioneers investment education, making complex financial concepts simple for everyday people to understand.",
"She transforms small business owners’ lives through comprehensive financial management training programs.",
"She has done exceptional work in teaching emergency fund creation strategies that have helped families build financial security.",
"She contributes outstandingly to financial inclusion by teaching underbanked communities how to maximize their money.",
"She has a revolutionary approach to retirement planning education, helping Nigerians prepare for financial independence in old age.",
"She pioneers teaching cryptocurrency and digital asset management to help people diversify their wealth.",
"She transforms household budgeting by teaching families how to stretch their income and save more money.",
"She shows exceptional leadership in teaching real estate investment strategies that help people build long-term wealth.",
"She does outstanding work in financial goal setting education, helping people create and achieve their money objectives.",
"She revolutionizes teaching multiple income streams, showing people how to diversify their earning potential.",
"She makes pioneering contributions to teaching tax optimization strategies that help people keep more of their hard-earned money.",
"She transforms lives by teaching insurance and risk management to protect families’ financial futures.",
];

// Generate random nominator (the person submitting) details
export const generateRandomNominator = () => {
  const firstName = nigerianNames.firstNames[Math.floor(Math.random() * nigerianNames.firstNames.length)]
  const lastName = nigerianNames.lastNames[Math.floor(Math.random() * nigerianNames.lastNames.length)]
  const reason = nominationReasons[Math.floor(Math.random() * nominationReasons.length)]
  
  // Generate varied email patterns for nominator
  const emailPatterns = [
    `${firstName.toLowerCase()}.${lastName.toLowerCase()}@gmail.com`,
    `${firstName.toLowerCase()}${lastName.toLowerCase()}@yahoo.com`,
    `${firstName.toLowerCase()}${Math.floor(Math.random() * 999)}@gmail.com`,
    `${firstName.toLowerCase()}_${lastName.toLowerCase()}@hotmail.com`,
    `${firstName.toLowerCase()}${lastName.toLowerCase()}${Math.floor(Math.random() * 99)}@gmail.com`,
    `${firstName.toLowerCase()}.${lastName.toLowerCase()}${Math.floor(Math.random() * 9)}@yahoo.com`,
    `${firstName.toLowerCase()}${Math.floor(Math.random() * 9999)}@gmail.com`,
    `${firstName.toLowerCase()}_${Math.floor(Math.random() * 999)}@hotmail.com`
  ]
  
  const shouldFillPhone = Math.random() > 0.2
  
  return {
    // Random nominator details (the person submitting)
    nominator_first: firstName,
    nominator_last: lastName,
    nominator_email: emailPatterns[Math.floor(Math.random() * emailPatterns.length)],
    nominator_phone: shouldFillPhone ? `+234${Math.floor(Math.random() * 900000000 + 700000000)}` : '',
    reason: reason
  }
}

// For backward compatibility
export const generateRandomContact = generateRandomNominator;